app/APIstripe/urls.py
from django.urls import path


app_name = "apistripe"

urlpatterns = []

app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls')),
]

app/payment/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import GetPaymentIntent, PayItem, PayOrder


app_name = "payment"

urlpatterns = [
    path('buy/', GetPaymentIntent.as_view(), name='get_intent'),
    path('order/<int:pk>/', PayOrder.as_view(), name='pay_order'),
    path('item/<int:pk>/', PayItem.as_view(), name='pay_item'),
    path('buy/success/', TemplateView.as_view(template_name='payment/success_payment.html'), name='success_payment'),
    path('buy/cancel/', TemplateView.as_view(template_name='payment/cancel_payment.html'), name='cancel_payment'),
]

app/payment/models.py
from django.db import models
from django.urls import reverse


class Item(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, db_index=True, verbose_name="Name")
    description = models.TextField(null=True, blank=True, db_index=True, verbose_name="Description")
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name="Price")
    currency = models.CharField(max_length=3, default='USD', choices=[
        ('usd', 'USD'),
        ('eur', 'EUR')
    ])

    def get_intent_url(self):
        return reverse('payment:get_intent', kwargs={'id': self.pk})


class Order(models.Model):
    items = models.ManyToManyField('Item')
    discount = models.ForeignKey('Discount', null=True, blank=True, on_delete=models.SET_NULL)
    tax = models.ForeignKey('Tax', null=True, blank=True, on_delete=models.SET_NULL)

    def get_intent_url(self):
        return reverse('payment:get_intent')

class Discount(models.Model):
    stripe_id = models.CharField(max_length=50)

class Tax(models.Model):
    stripe_id = models.CharField(max_length=50)

app/payment/views.py
import json
from django.db.models import Sum
from django.http import HttpRequest, JsonResponse
from django.views.generic import View, DetailView
from .utils import get_stripe_session, get_stripe_intent
from .models import Item, Order


class GetPaymentIntent(View):

    def get(self, request: HttpRequest, *args, **kwargs):
        id_item = self.kwargs.get('id')
        item_obj = Item.objects.get(id=int(id_item))
        session_pay = get_stripe_session(item_obj, request)
        return JsonResponse(data={'session': session_pay})

    def post(self, request: HttpRequest):
        data = json.loads(request.body)
        order_id = data['order_id']
        order = Order.objects.filter(id=order_id).annotate(
            total_amount=Sum('items__price')
        ).first()
        intent = get_stripe_intent(order)
        return JsonResponse({'clientSecret': intent.client_secret})


class PayItem(DetailView):
    template_name = 'payment/buy_item.html'
    context_object_name = 'item'
    model = Item


class PayOrder(DetailView):
    template_name = 'payment/buy_order.html'
    context_object_name = 'order'
    model = Order

    def get_queryset(self):
        order_id = self.kwargs.get('pk')
        order = Order.objects.filter(id=order_id).annotate(
            total_amount=Sum('items__price'),
        )
        return order

app/payment/templates/payment/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>

<body>
{% block body %}

{% endblock %}

{% block script %}

{% endblock %}
</body>

</html>

app/payment/templates/payment/buy_item.html
{% extends 'payment/base.html' %}

{% block title %}
  {{ item.name }}
{% endblock %}

{% block body %}
  <div>
    <p>Name: {{ item.name }}</p>
    <p>Description: {{ item.description }}</p>
    <p>Price: {{ item.price }} {{ item.currency }}</p>
  </div>
  <div>
    <button id="buy-button">Buy</button>
  </div>
{% endblock %}

{% block script %}
<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
  var stripe = Stripe('pk_test_51QxNF9AL2OLARfzR3Jrk1O4qabzPA2IAN1SOXjeRsNR3CNIhv5v4b61zp6HerS7BWT30w41PUbAZZ5bOFVqk4J3j00EXOsaEnv');
  var buyButton = document.getElementById('buy-button');
  buyButton.addEventListener('click', function() {
    fetch('{{ item.get_session_url }}', { method: 'GET' })
      .then(response => response.json())
      .then(session => {
        stripe.redirectToCheckout({ sessionId: session.session.id });
      })
      .catch(error => {
        console.error('Error:', error);
        alert('Ошибка при оплате');
      });
  });
</script>
{% endblock %}

app/payment/templates/payment/buy_order.html
{% extends 'payment/base.html' %}
{% load static %}

{% block title %}
  {{ order.name }}
{% endblock %}

{% block body %}
  <div>
    <table>
      <thead>Order {{ order.pk }}</thead>
      <tbody>
        {% for item in order.items.all %}
        <p>Item: {{ item.name }}</p>
        <p>Description: {{ item.description }}</p>
        <P>Price: {{ item.price }} {{ item.currency }}</P>
      {% endfor %}
      </tbody>
      <p>Total amount order: {{ order.total_amount }} USD</p>
    </table>

  </div>
  <div>
    <!-- Display a payment form -->
    <form id="payment-form">
      <div id="payment-element">
        <!--Stripe.js injects the Payment Element-->
      </div>
      <button id="submit">
        <div class="spinner hidden" id="spinner"></div>
        <span id="button-text">Pay now</span>
      </button>
      <div id="payment-message" class="hidden"></div>
    </form>

  </div>
{% endblock %}

{% block script %}
<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
  const url = "{{ order.get_intent_url }}"
  const items = { order_id: {{ order.pk }}, amount: {{ order.total_amount }} };
  const return_success_url = "{% url 'payment:success_payment' %}"
</script>
<script src="{% static 'js/stripe.js' %}"></script>
{% endblock %}

app/payment/templates/payment/cancel_payment.html
{% extends 'payment/base.html' %}

{% block title %}
  Success cancel
{% endblock %}

{% block body %}
  <div>
    <p>Payment Cancel</p>
    <p><a href="{% url 'admin:index' %}">Go to admin</a></p>
  </div>
{% endblock %}

app/payment/templates/payment/success_payment.html
{% extends 'payment/base.html' %}

{% block title %}
  Success payment
{% endblock %}

{% block body %}
  <div>
    <p>Payment Success</p>
    <p><a href="{% url 'admin:index' %}">Go to admin</a></p>
  </div>
{% endblock %}